# PostgreSQL
development:
  adapter: postgresql
  encoding: unicode
  database: fulcrum_development
  pool: 5
  username: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: fulcrum_test
  pool: 5
  username: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: fulcrum_production
  pool: 5
  username: postgres