# PostgreSQL
development:
  adapter: postgresql
  encoding: unicode
  database: fulcrum
  pool: 5
  username: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: fulcrum
  pool: 5
  username: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: fulcrum
  pool: 5
  username: postgres